# Generated by Django 3.1.7 on 2021-04-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.FloatField(default=0)),
                ('productImage', models.ImageField(upload_to='shop/images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
