# Generated by Django 3.1.7 on 2021-04-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoDesc', models.CharField(max_length=25)),
                ('promoImage', models.ImageField(upload_to='promo/images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
