# Generated by Django 3.1.7 on 2021-04-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_productslug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
