# Generated by Django 3.1.7 on 2021-04-16 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shipping_address',
        ),
    ]
